// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace OurMemory.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IntitEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntitEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201511281520162_IntitEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
